# Generated by Django 3.1.5 on 2021-01-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210129_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='dopps',
            new_name='doppss',
        ),
    ]
