# Generated by Django 3.1.5 on 2021-01-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210129_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='doppss',
            new_name='dopss',
        ),
    ]
