# Generated by Django 3.1.5 on 2021-02-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210202_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='dopss',
            new_name='apps',
        ),
    ]
