# Generated by Django 3.1.5 on 2021-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210202_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='price_per_kilogram',
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
