# Generated by Django 3.1.5 on 2021-01-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price_per_kilogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='structure',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
